import pytest
from fastapi import HTTPException

from app.services.clubs.players import TransfermarktClubPlayers


def test_clubs_players_id_0():
    tfmkt = TransfermarktClubPlayers(club_id="0")

    with pytest.raises(HTTPException):
        tfmkt.get_club_players()


def test_clubs_players_id_210_season_2017():
    tfmkt = TransfermarktClubPlayers(club_id="210", season_id="2017")
    result = tfmkt.get_club_players()

    expected = {
        "id": "210",
        "clubName": "Grêmio Foot-Ball Porto Alegrense",
        "seasonYear": "2017",
        "players": [
            {
                "id": "29368",
                "name": "Léo Moura",
                "position": "Defence",
                "age": "39",
                "nationality": ["Brazil"],
                "marketValue": "€500k",
            },
            {
                "id": "52313",
                "name": "Marcelo Grohe",
                "position": "Goalkeeper",
                "age": "31",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€4.00m",
            },
            {
                "id": "67886",
                "name": "Paulo Victor",
                "position": "Goalkeeper",
                "age": "31",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€900k",
            },
            {
                "id": "95747",
                "name": "Bruno Grassi",
                "position": "Goalkeeper",
                "age": "31",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€100k",
            },
            {
                "id": "288415",
                "name": "Léo Jardim",
                "position": "Goalkeeper",
                "age": "23",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€100k",
            },
            {
                "id": "555016",
                "name": "Brenno",
                "position": "Goalkeeper",
                "age": "19",
                "nationality": ["Brazil"],
                "marketValue": "-",
            },
            {
                "id": "32568",
                "name": "Pedro Geromel",
                "position": "Centre-Back",
                "age": "32",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€5.00m",
                "status": "Knee Injury - Return unknown",
            },
            {
                "id": "145400",
                "name": "Walter Kannemann",
                "position": "Centre-Back",
                "age": "27",
                "nationality": ["Argentina", "Italy"],
                "marketValue": "€2.50m",
            },
            {
                "id": "52844",
                "name": "Marcelo Oliveira",
                "position": "Centre-Back",
                "age": "31",
                "nationality": ["Brazil"],
                "marketValue": "€1.00m",
            },
            {
                "id": "80499",
                "name": "Paulo Miranda",
                "position": "Centre-Back",
                "age": "29",
                "nationality": ["Brazil"],
                "marketValue": "€1.00m",
            },
            {
                "id": "256453",
                "name": "Bressan",
                "position": "Centre-Back",
                "age": "25",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€1.00m",
            },
            {
                "id": "292152",
                "name": "Rafael Thyere",
                "position": "Centre-Back",
                "age": "25",
                "nationality": ["Brazil"],
                "marketValue": "€700k",
            },
            {
                "id": "445101",
                "name": "Rodrigues",
                "position": "Centre-Back",
                "age": "20",
                "nationality": ["Brazil"],
                "marketValue": "€200k",
            },
            {
                "id": "216071",
                "name": "Gabriel",
                "position": "Centre-Back",
                "age": "29",
                "nationality": ["Brazil"],
                "marketValue": "€100k",
                "status": "Knee Surgery - Return unknown",
            },
            {
                "id": "68679",
                "name": "Bruno Rodrigo",
                "position": "Centre-Back",
                "age": "33",
                "nationality": ["Brazil"],
                "marketValue": "-",
            },
            {
                "id": "476366",
                "name": "Denilson",
                "position": "Centre-Back",
                "age": "23",
                "nationality": ["Brazil"],
                "marketValue": "-",
            },
            {
                "id": "555634",
                "name": "Derlan",
                "position": "Centre-Back",
                "age": "22",
                "nationality": ["Brazil"],
                "marketValue": "-",
            },
            {
                "id": "182216",
                "name": "Bruno Cortez",
                "position": "Left-Back",
                "age": "31",
                "nationality": ["Brazil"],
                "marketValue": "€1.75m",
            },
            {
                "id": "406676",
                "name": "Juninho Capixaba",
                "position": "Left-Back",
                "age": "20",
                "nationality": ["Brazil"],
                "marketValue": "€900k",
                "joined": (
                    "Returned after loan spell with Fortaleza Esporte Clube; date: Dec 31, 2022; fee: End of loan"
                ),
            },
            {
                "id": "322781",
                "name": "Breno Lorran",
                "position": "Left-Back",
                "age": "23",
                "nationality": ["Brazil"],
                "marketValue": "€600k",
            },
            {
                "id": "351738",
                "name": "Lincoln",
                "position": "Left-Back",
                "age": "19",
                "nationality": ["Brazil"],
                "marketValue": "€500k",
                "status": "Cruciate Ligament Rupture - Return expected on Oct 9, 2023",
            },
            {
                "id": "552548",
                "name": "Guilherme Guedes",
                "position": "Left-Back",
                "age": "19",
                "nationality": ["Brazil"],
                "marketValue": "-",
                "joined": (
                    "Returned after loan spell with Esporte Clube Juventude; date: Apr 17, 2023; fee: End of loan"
                ),
            },
            {
                "id": "75083",
                "name": "Edílson",
                "position": "Right-Back",
                "age": "31",
                "nationality": ["Brazil"],
                "marketValue": "€1.50m",
            },
            {
                "id": "177845",
                "name": "Madson",
                "position": "Right-Back",
                "age": "26",
                "nationality": ["Brazil"],
                "marketValue": "€1.25m",
            },
            {
                "id": "347016",
                "name": "Léo Gomes",
                "position": "Right-Back",
                "age": "22",
                "nationality": ["Brazil"],
                "marketValue": "€200k",
            },
            {
                "id": "555012",
                "name": "Felipe Albuquerque",
                "position": "Right-Back",
                "age": "18",
                "nationality": ["Brazil"],
                "marketValue": "-",
            },
            {
                "id": "366948",
                "name": "Jailson",
                "position": "Defensive Midfield",
                "age": "22",
                "nationality": ["Brazil"],
                "marketValue": "€2.50m",
            },
            {
                "id": "435186",
                "name": "Michel",
                "position": "Defensive Midfield",
                "age": "28",
                "nationality": ["Brazil"],
                "marketValue": "€1.50m",
            },
            {
                "id": "376867",
                "name": "Moisés Gaúcho",
                "position": "Defensive Midfield",
                "age": "23",
                "nationality": ["Brazil"],
                "marketValue": "€100k",
            },
            {
                "id": "405727",
                "name": "Kaio",
                "position": "Defensive Midfield",
                "age": "23",
                "nationality": ["Brazil"],
                "marketValue": "€100k",
            },
            {
                "id": "520629",
                "name": "Filipe Machado",
                "position": "Defensive Midfield",
                "age": "22",
                "nationality": ["Brazil"],
                "marketValue": "€50k",
            },
            {
                "id": "362842",
                "name": "Arthur Melo",
                "position": "Central Midfield",
                "age": "21",
                "nationality": ["Brazil"],
                "marketValue": "€30.00m",
            },
            {
                "id": "258070",
                "name": "Ramiro",
                "position": "Central Midfield",
                "age": "25",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€5.00m",
            },
            {
                "id": "17663",
                "name": "Cícero",
                "position": "Central Midfield",
                "age": "33",
                "nationality": ["Brazil"],
                "marketValue": "€2.00m",
            },
            {
                "id": "50047",
                "name": "Maicon",
                "position": "Central Midfield",
                "age": "32",
                "nationality": ["Brazil"],
                "marketValue": "€1.75m",
            },
            {
                "id": "392487",
                "name": "Thaciano",
                "position": "Central Midfield",
                "age": "23",
                "nationality": ["Brazil"],
                "marketValue": "€200k",
                "joined": "Returned after loan spell with Altay SK; date: Jun 30, 2022; fee: End of loan",
            },
            {
                "id": "552549",
                "name": "Matheus Henrique",
                "position": "Central Midfield",
                "age": "20",
                "nationality": ["Brazil"],
                "marketValue": "€50k",
                "joined": "Returned after loan spell with US Sassuolo; date: Jun 30, 2022; fee: End of loan",
            },
            {
                "id": "313106",
                "name": "Luan",
                "position": "Attacking Midfield",
                "age": "25",
                "nationality": ["Brazil"],
                "marketValue": "€20.00m",
            },
            {
                "id": "34332",
                "name": "Douglas",
                "position": "Attacking Midfield",
                "age": "36",
                "nationality": ["Brazil"],
                "marketValue": "€600k",
            },
            {
                "id": "387611",
                "name": "Lima",
                "position": "Attacking Midfield",
                "age": "22",
                "nationality": ["Brazil"],
                "marketValue": "€400k",
            },
            {
                "id": "561214",
                "name": "Thonny  Anderson",
                "position": "Attacking Midfield",
                "age": "20",
                "nationality": ["Brazil"],
                "marketValue": "€400k",
            },
            {
                "id": "405726",
                "name": "Felipe Tontini",
                "position": "Attacking Midfield",
                "age": "22",
                "nationality": ["Brazil"],
                "marketValue": "€200k",
            },
            {
                "id": "351903",
                "name": "Jean Pyerre",
                "position": "Attacking Midfield",
                "age": "20",
                "nationality": ["Brazil"],
                "marketValue": "-",
                "joined": "Returned after loan spell with Avaí FC; date: Dec 31, 2022; fee: End of loan",
            },
            {
                "id": "627099",
                "name": "Isaque",
                "position": "Attacking Midfield",
                "age": "21",
                "nationality": ["Brazil"],
                "marketValue": "-",
                "joined": (
                    "Returned after loan spell with Guarani Futebol Clube (SP); date: Dec 31, 2022; fee: End of loan"
                ),
            },
            {
                "id": "321239",
                "name": "Everton",
                "position": "Left Winger",
                "age": "22",
                "nationality": ["Brazil"],
                "marketValue": "€7.00m",
            },
            {
                "id": "76902",
                "name": "Fernandinho",
                "position": "Left Winger",
                "age": "32",
                "nationality": ["Brazil"],
                "marketValue": "€1.20m",
            },
            {
                "id": "54183",
                "name": "Maicosuel",
                "position": "Left Winger",
                "age": "32",
                "nationality": ["Brazil"],
                "marketValue": "€1.00m",
            },
            {
                "id": "552547",
                "name": "Lucas Poletto",
                "position": "Left Winger",
                "age": "23",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€50k",
            },
            {
                "id": "520636",
                "name": "Dionathã",
                "position": "Left Winger",
                "age": "20",
                "nationality": ["Brazil"],
                "marketValue": "-",
            },
            {
                "id": "520662",
                "name": "Pepê",
                "position": "Left Winger",
                "age": "21",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "-",
            },
            {
                "id": "229736",
                "name": "Alisson",
                "position": "Right Winger",
                "age": "25",
                "nationality": ["Brazil"],
                "marketValue": "€2.50m",
            },
            {
                "id": "74758",
                "name": "Marinho",
                "position": "Right Winger",
                "age": "28",
                "nationality": ["Brazil"],
                "marketValue": "€1.20m",
            },
            {
                "id": "553470",
                "name": "Vico",
                "position": "Right Winger",
                "age": "21",
                "nationality": ["Brazil"],
                "marketValue": "€50k",
            },
            {
                "id": "104509",
                "name": "André Felipe",
                "position": "Centre-Forward",
                "age": "27",
                "nationality": ["Brazil"],
                "marketValue": "€3.50m",
            },
            {
                "id": "58516",
                "name": "Lucas Barrios",
                "position": "Centre-Forward",
                "age": "33",
                "nationality": ["Paraguay", "Argentina"],
                "marketValue": "€1.75m",
            },
            {
                "id": "195004",
                "name": "Hernane",
                "position": "Centre-Forward",
                "age": "32",
                "nationality": ["Brazil"],
                "marketValue": "€1.50m",
            },
            {
                "id": "80815",
                "name": "Jael",
                "position": "Centre-Forward",
                "age": "29",
                "nationality": ["Brazil"],
                "marketValue": "€800k",
            },
            {
                "id": "203136",
                "name": "Yuri Mamute",
                "position": "Centre-Forward",
                "age": "23",
                "nationality": ["Brazil"],
                "marketValue": "€600k",
            },
            {
                "id": "379877",
                "name": "Luis Henrique",
                "position": "Centre-Forward",
                "age": "20",
                "nationality": ["Brazil", "Italy"],
                "marketValue": "€400k",
            },
        ],
    }

    assert result == expected
