from app.schemas.players.absences import PlayerAbsences as PlayerAbsences
from app.schemas.players.injuries import PlayerInjuries as PlayerInjuries
from app.schemas.players.market_value import PlayerMarketValue as PlayerMarketValue
from app.schemas.players.matches import PlayerMatches as PlayerMatches
from app.schemas.players.national_career import PlayerNationalCareer as PlayerNationalCareer
from app.schemas.players.profile import PlayerProfile as PlayerProfile
from app.schemas.players.search import PlayerSearch as PlayerSearch
from app.schemas.players.stats import PlayerStats as PlayerStats
from app.schemas.players.transfers import PlayerTransfers as PlayerTransfers
