from datetime import datetime

import pytest
from fastapi import HTTPException

from app.services.players.stats import TransfermarktPlayerStats


def test_players_profile_id_0():
    tfmkt = TransfermarktPlayerStats(player_id="0")

    with pytest.raises(HTTPException):
        tfmkt.get_player_stats()


def test_players_profile_id_3373():
    tfmkt = TransfermarktPlayerStats(player_id="3373")
    result = tfmkt.get_player_stats()
    last_update = result.pop("lastUpdate")

    expected = {
        "id": "3373",
        "stats": [
            {
                "season": "2015",
                "competitionID": "BRA1",
                "competitionName": "Série A",
                "clubID": "2462",
                "clubName": "Fluminense Football Club",
                "appearances": "7",
                "goals": "-",
                "assists": "-",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "468'",
            },
            {
                "season": "14/15",
                "competitionID": "POME",
                "competitionName": "Liguilla Clausura",
                "clubID": "4961",
                "clubName": "Querétaro FC",
                "appearances": "5",
                "goals": "1",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "278'",
            },
            {
                "season": "14/15",
                "competitionID": "MEX1",
                "competitionName": "Liga MX Clausura",
                "clubID": "4961",
                "clubName": "Querétaro FC",
                "appearances": "11",
                "goals": "4",
                "assists": "4",
                "yellowCards": "4",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "592'",
            },
            {
                "season": "14/15",
                "competitionID": "MXCC",
                "competitionName": "Copa MX Clausura",
                "clubID": "4961",
                "clubName": "Querétaro FC",
                "appearances": "3",
                "goals": "-",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "251'",
            },
            {
                "season": "14/15",
                "competitionID": "MEXA",
                "competitionName": "Liga MX Apertura",
                "clubID": "4961",
                "clubName": "Querétaro FC",
                "appearances": "9",
                "goals": "3",
                "assists": "2",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "767'",
            },
            {
                "season": "14/15",
                "competitionID": "MXCA",
                "competitionName": "Copa MX Apertura",
                "clubID": "4961",
                "clubName": "Querétaro FC",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "2014",
                "competitionID": "RECO",
                "competitionName": "Recopa Sudamericana",
                "clubID": "330",
                "clubName": "Clube Atlético Mineiro",
                "appearances": "2",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "110'",
            },
            {
                "season": "2014",
                "competitionID": "CLI",
                "competitionName": "Libertadores",
                "clubID": "330",
                "clubName": "Clube Atlético Mineiro",
                "appearances": "7",
                "goals": "1",
                "assists": "2",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "613'",
            },
            {
                "season": "2014",
                "competitionID": "BRA1",
                "competitionName": "Série A",
                "clubID": "330",
                "clubName": "Clube Atlético Mineiro",
                "appearances": "2",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "156'",
            },
            {
                "season": "13/14",
                "competitionID": "KLUB",
                "competitionName": "Club World Cup",
                "clubID": "330",
                "clubName": "Clube Atlético Mineiro",
                "appearances": "2",
                "goals": "2",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "1",
                "minutesPlayed": "177'",
            },
            {
                "season": "2013",
                "competitionID": "BRA1",
                "competitionName": "Série A",
                "clubID": "330",
                "clubName": "Clube Atlético Mineiro",
                "appearances": "14",
                "goals": "8",
                "assists": "2",
                "yellowCards": "6",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "1.256'",
            },
            {
                "season": "2013",
                "competitionID": "BRC",
                "competitionName": "Copa do Brasil",
                "clubID": "330",
                "clubName": "Clube Atlético Mineiro",
                "appearances": "2",
                "goals": "-",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "2013",
                "competitionID": "CLI",
                "competitionName": "Libertadores",
                "clubID": "330",
                "clubName": "Clube Atlético Mineiro",
                "appearances": "14",
                "goals": "4",
                "assists": "7",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "1.265'",
            },
            {
                "season": "2012",
                "competitionID": "BRA1",
                "competitionName": "Série A",
                "clubID": "330",
                "clubName": "Clube Atlético Mineiro",
                "appearances": "32",
                "goals": "9",
                "assists": "15",
                "yellowCards": "5",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.867'",
            },
            {
                "season": "2012",
                "competitionID": "BRA1",
                "competitionName": "Série A",
                "clubID": "614",
                "clubName": "CR Flamengo",
                "appearances": "2",
                "goals": "1",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "166'",
            },
            {
                "season": "2012",
                "competitionID": "CLI",
                "competitionName": "Libertadores",
                "clubID": "614",
                "clubName": "CR Flamengo",
                "appearances": "8",
                "goals": "2",
                "assists": "6",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "720'",
            },
            {
                "season": "2011",
                "competitionID": "BRA1",
                "competitionName": "Série A",
                "clubID": "614",
                "clubName": "CR Flamengo",
                "appearances": "31",
                "goals": "14",
                "assists": "7",
                "yellowCards": "11",
                "secondYellowCards": "-",
                "redCards": "1",
                "minutesPlayed": "2.738'",
            },
            {
                "season": "2011",
                "competitionID": "CS",
                "competitionName": "Copa Sudamericana",
                "clubID": "614",
                "clubName": "CR Flamengo",
                "appearances": "3",
                "goals": "2",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "151'",
            },
            {
                "season": "10/11",
                "competitionID": "IT1",
                "competitionName": "Serie A",
                "clubID": "5",
                "clubName": "AC Milan",
                "appearances": "11",
                "goals": "-",
                "assists": "3",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "605'",
            },
            {
                "season": "10/11",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "5",
                "clubName": "AC Milan",
                "appearances": "5",
                "goals": "1",
                "assists": "1",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "317'",
            },
            {
                "season": "09/10",
                "competitionID": "IT1",
                "competitionName": "Serie A",
                "clubID": "5",
                "clubName": "AC Milan",
                "appearances": "36",
                "goals": "12",
                "assists": "18",
                "yellowCards": "6",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.897'",
            },
            {
                "season": "09/10",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "5",
                "clubName": "AC Milan",
                "appearances": "7",
                "goals": "3",
                "assists": "1",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "584'",
            },
            {
                "season": "08/09",
                "competitionID": "IT1",
                "competitionName": "Serie A",
                "clubID": "5",
                "clubName": "AC Milan",
                "appearances": "29",
                "goals": "8",
                "assists": "5",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "1.605'",
            },
            {
                "season": "08/09",
                "competitionID": "UEFA",
                "competitionName": "UEFA Cup",
                "clubID": "5",
                "clubName": "AC Milan",
                "appearances": "6",
                "goals": "2",
                "assists": "1",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "255'",
            },
            {
                "season": "08/09",
                "competitionID": "CIT",
                "competitionName": "Italy Cup",
                "clubID": "5",
                "clubName": "AC Milan",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "120'",
            },
            {
                "season": "07/08",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "17",
                "goals": "8",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "1.174'",
            },
            {
                "season": "07/08",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "8",
                "goals": "1",
                "assists": "3",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "591'",
            },
            {
                "season": "07/08",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "15'",
            },
            {
                "season": "06/07",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "32",
                "goals": "21",
                "assists": "9",
                "yellowCards": "8",
                "secondYellowCards": "-",
                "redCards": "1",
                "minutesPlayed": "2.742'",
            },
            {
                "season": "06/07",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "4",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "360'",
            },
            {
                "season": "06/07",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "8",
                "goals": "2",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "720'",
            },
            {
                "season": "06/07",
                "competitionID": "KLUB",
                "competitionName": "Club World Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "1",
                "assists": "1",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "06/07",
                "competitionID": "USC",
                "competitionName": "UEFA Super Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "06/07",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "-",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "05/06",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "12",
                "goals": "7",
                "assists": "5",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "1.079'",
            },
            {
                "season": "05/06",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "29",
                "goals": "17",
                "assists": "18",
                "yellowCards": "5",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.527'",
            },
            {
                "season": "05/06",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "1",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "1",
                "minutesPlayed": "128'",
            },
            {
                "season": "05/06",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "1",
                "assists": "1",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "04/05",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "35",
                "goals": "9",
                "assists": "15",
                "yellowCards": "5",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "3.071'",
            },
            {
                "season": "04/05",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "7",
                "goals": "4",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "603'",
            },
            {
                "season": "03/04",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "6",
                "goals": "3",
                "assists": "3",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "481'",
            },
            {
                "season": "03/04",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "32",
                "goals": "15",
                "assists": "6",
                "yellowCards": "8",
                "secondYellowCards": "1",
                "redCards": "-",
                "minutesPlayed": "2.678'",
            },
            {
                "season": "03/04",
                "competitionID": "UEFA",
                "competitionName": "UEFA Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "7",
                "goals": "4",
                "assists": "2",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "536'",
            },
            {
                "season": "02/03",
                "competitionID": "FRC",
                "competitionName": "Coupe de France",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "5",
                "goals": "3",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "413'",
            },
            {
                "season": "02/03",
                "competitionID": "FR1",
                "competitionName": "Ligue 1",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "27",
                "goals": "8",
                "assists": "8",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "1",
                "minutesPlayed": "1.924'",
            },
            {
                "season": "02/03",
                "competitionID": "UEFA",
                "competitionName": "UEFA Cup",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "4",
                "goals": "1",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "332'",
            },
            {
                "season": "02/03",
                "competitionID": "FRL",
                "competitionName": "Coupe de la Ligue",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "01/02",
                "competitionID": "FR1",
                "competitionName": "Division 1",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "28",
                "goals": "9",
                "assists": "7",
                "yellowCards": "7",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "1.917'",
            },
            {
                "season": "01/02",
                "competitionID": "FRC",
                "competitionName": "Coupe de France",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "2",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "210'",
            },
            {
                "season": "01/02",
                "competitionID": "FRL",
                "competitionName": "Coupe de la Ligue",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "4",
                "goals": "2",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "153'",
            },
            {
                "season": "01/02",
                "competitionID": "UEFA",
                "competitionName": "UEFA Cup",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "6",
                "goals": "2",
                "assists": "-",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "492'",
            },
            {
                "season": "1998",
                "competitionID": "CLI",
                "competitionName": "Libertadores",
                "clubID": "210",
                "clubName": "Grêmio Foot-Ball Porto Alegrense",
                "appearances": "10",
                "goals": "1",
                "assists": "1",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "766'",
            },
        ],
    }

    assert isinstance(last_update, datetime)
    assert result == expected


def test_players_profile_id_28003():
    tfmkt = TransfermarktPlayerStats(player_id="28003")
    result = tfmkt.get_player_stats()
    last_update = result.pop("lastUpdate")

    expected = {
        "id": "28003",
        "stats": [
            {
                "season": "2023",
                "competitionID": "MLS1",
                "competitionName": "MLS",
                "clubID": "69261",
                "clubName": "Inter Miami CF",
                "appearances": "3",
                "goals": "1",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "210'",
            },
            {
                "season": "2023",
                "competitionID": "MLSP",
                "competitionName": "US Open Cup",
                "clubID": "69261",
                "clubName": "Inter Miami CF",
                "appearances": "1",
                "goals": "-",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "120'",
            },
            {
                "season": "2023",
                "competitionID": "USMX",
                "competitionName": "Leagues Cup",
                "clubID": "69261",
                "clubName": "Inter Miami CF",
                "appearances": "7",
                "goals": "10",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "624'",
            },
            {
                "season": "22/23",
                "competitionID": "FR1",
                "competitionName": "Ligue 1",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "32",
                "goals": "16",
                "assists": "16",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.842'",
            },
            {
                "season": "22/23",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "7",
                "goals": "4",
                "assists": "4",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "615'",
            },
            {
                "season": "22/23",
                "competitionID": "FRC",
                "competitionName": "Coupe de France",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "22/23",
                "competitionID": "FRCH",
                "competitionName": "Trophée des Champions",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "1",
                "goals": "1",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "21/22",
                "competitionID": "FR1",
                "competitionName": "Ligue 1",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "26",
                "goals": "6",
                "assists": "15",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.152'",
            },
            {
                "season": "21/22",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "7",
                "goals": "5",
                "assists": "-",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "630'",
            },
            {
                "season": "21/22",
                "competitionID": "FRC",
                "competitionName": "Coupe de France",
                "clubID": "583",
                "clubName": "Paris Saint-Germain",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "20/21",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "35",
                "goals": "30",
                "assists": "11",
                "yellowCards": "4",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "3.022'",
            },
            {
                "season": "20/21",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "5",
                "goals": "3",
                "assists": "1",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "510'",
            },
            {
                "season": "20/21",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "6",
                "goals": "5",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "540'",
            },
            {
                "season": "20/21",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "1",
                "minutesPlayed": "120'",
            },
            {
                "season": "19/20",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "8",
                "goals": "3",
                "assists": "4",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "661'",
            },
            {
                "season": "19/20",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "33",
                "goals": "25",
                "assists": "22",
                "yellowCards": "4",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.879'",
            },
            {
                "season": "19/20",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "2",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "19/20",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "1",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "18/19",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "5",
                "goals": "3",
                "assists": "3",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "387'",
            },
            {
                "season": "18/19",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "34",
                "goals": "36",
                "assists": "14",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.709'",
            },
            {
                "season": "18/19",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "10",
                "goals": "12",
                "assists": "3",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "837'",
            },
            {
                "season": "18/19",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "-",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "17/18",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "36",
                "goals": "34",
                "assists": "14",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.996'",
            },
            {
                "season": "17/18",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "6",
                "goals": "4",
                "assists": "4",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "509'",
            },
            {
                "season": "17/18",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "10",
                "goals": "6",
                "assists": "2",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "783'",
            },
            {
                "season": "17/18",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "1",
                "assists": "-",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "16/17",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "7",
                "goals": "5",
                "assists": "4",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "630'",
            },
            {
                "season": "16/17",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "34",
                "goals": "37",
                "assists": "12",
                "yellowCards": "6",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.832'",
            },
            {
                "season": "16/17",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "9",
                "goals": "11",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "810'",
            },
            {
                "season": "16/17",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "1",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "15/16",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "5",
                "goals": "5",
                "assists": "6",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "480'",
            },
            {
                "season": "15/16",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "33",
                "goals": "26",
                "assists": "16",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.729'",
            },
            {
                "season": "15/16",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "7",
                "goals": "6",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "630'",
            },
            {
                "season": "15/16",
                "competitionID": "KLUB",
                "competitionName": "Club World Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "1",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "15/16",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "1",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "15/16",
                "competitionID": "USC",
                "competitionName": "UEFA Super Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "2",
                "assists": "1",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "120'",
            },
            {
                "season": "14/15",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "13",
                "goals": "10",
                "assists": "6",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "1.146'",
            },
            {
                "season": "14/15",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "6",
                "goals": "5",
                "assists": "4",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "540'",
            },
            {
                "season": "14/15",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "38",
                "goals": "43",
                "assists": "21",
                "yellowCards": "4",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "3.374'",
            },
            {
                "season": "13/14",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "31",
                "goals": "28",
                "assists": "11",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.501'",
            },
            {
                "season": "13/14",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "6",
                "goals": "5",
                "assists": "3",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "476'",
            },
            {
                "season": "13/14",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "7",
                "goals": "8",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "630'",
            },
            {
                "season": "13/14",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "135'",
            },
            {
                "season": "12/13",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "32",
                "goals": "46",
                "assists": "13",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.626'",
            },
            {
                "season": "12/13",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "11",
                "goals": "8",
                "assists": "3",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "821'",
            },
            {
                "season": "12/13",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "5",
                "goals": "4",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "443'",
            },
            {
                "season": "12/13",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "2",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "11/12",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "7",
                "goals": "3",
                "assists": "4",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "512'",
            },
            {
                "season": "11/12",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "37",
                "goals": "50",
                "assists": "19",
                "yellowCards": "6",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "3.269'",
            },
            {
                "season": "11/12",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "11",
                "goals": "14",
                "assists": "5",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "990'",
            },
            {
                "season": "11/12",
                "competitionID": "KLUB",
                "competitionName": "Club World Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "2",
                "assists": "1",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "11/12",
                "competitionID": "USC",
                "competitionName": "UEFA Super Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "1",
                "assists": "1",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "11/12",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "3",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "10/11",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "13",
                "goals": "12",
                "assists": "4",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "1.048'",
            },
            {
                "season": "10/11",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "33",
                "goals": "31",
                "assists": "21",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.861'",
            },
            {
                "season": "10/11",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "7",
                "goals": "7",
                "assists": "2",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "542'",
            },
            {
                "season": "10/11",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "3",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "128'",
            },
            {
                "season": "09/10",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "35",
                "goals": "34",
                "assists": "11",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.840'",
            },
            {
                "season": "09/10",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "11",
                "goals": "8",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "986'",
            },
            {
                "season": "09/10",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "3",
                "goals": "1",
                "assists": "-",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "209'",
            },
            {
                "season": "09/10",
                "competitionID": "KLUB",
                "competitionName": "Club World Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "2",
                "assists": "-",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "157'",
            },
            {
                "season": "09/10",
                "competitionID": "USC",
                "competitionName": "UEFA Super Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "-",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "120'",
            },
            {
                "season": "09/10",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "2",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "08/09",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "12",
                "goals": "9",
                "assists": "5",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "927'",
            },
            {
                "season": "08/09",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "8",
                "goals": "6",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "450'",
            },
            {
                "season": "08/09",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "31",
                "goals": "23",
                "assists": "13",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.513'",
            },
            {
                "season": "07/08",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "28",
                "goals": "10",
                "assists": "14",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.003'",
            },
            {
                "season": "07/08",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "9",
                "goals": "6",
                "assists": "2",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "726'",
            },
            {
                "season": "07/08",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "3",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "225'",
            },
            {
                "season": "06/07",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "26",
                "goals": "14",
                "assists": "2",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "2.001'",
            },
            {
                "season": "06/07",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "2",
                "assists": "1",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "166'",
            },
            {
                "season": "06/07",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "5",
                "goals": "1",
                "assists": "-",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "385'",
            },
            {
                "season": "06/07",
                "competitionID": "USC",
                "competitionName": "UEFA Super Cup",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "06/07",
                "competitionID": "SUC",
                "competitionName": "Supercopa",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "121'",
            },
            {
                "season": "05/06",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "6",
                "goals": "1",
                "assists": "2",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "322'",
            },
            {
                "season": "05/06",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "17",
                "goals": "6",
                "assists": "2",
                "yellowCards": "2",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "912'",
            },
            {
                "season": "05/06",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "2",
                "goals": "1",
                "assists": "1",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "180'",
            },
            {
                "season": "04/05",
                "competitionID": "ES3C",
                "competitionName": "2ª B - Grupo III",
                "clubID": "2464",
                "clubName": "FC Barcelona B",
                "appearances": "17",
                "goals": "6",
                "assists": "1",
                "yellowCards": "3",
                "secondYellowCards": "-",
                "redCards": "1",
                "minutesPlayed": "1.515'",
            },
            {
                "season": "04/05",
                "competitionID": "ES1",
                "competitionName": "LaLiga",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "7",
                "goals": "1",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "75'",
            },
            {
                "season": "04/05",
                "competitionID": "CL",
                "competitionName": "Champions League",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "90'",
            },
            {
                "season": "04/05",
                "competitionID": "CDR",
                "competitionName": "Copa del Rey",
                "clubID": "131",
                "clubName": "FC Barcelona",
                "appearances": "1",
                "goals": "-",
                "assists": "-",
                "yellowCards": "-",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "73'",
            },
            {
                "season": "03/04",
                "competitionID": "ES3C",
                "competitionName": "2ª B - Grupo III",
                "clubID": "2464",
                "clubName": "FC Barcelona B",
                "appearances": "5",
                "goals": "-",
                "assists": "-",
                "yellowCards": "1",
                "secondYellowCards": "-",
                "redCards": "-",
                "minutesPlayed": "404'",
            },
        ],
        "lastUpdate": "2023-09-15T17:17:48.067606",
    }

    assert isinstance(last_update, datetime)
    assert result == expected
