name: Code Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: ruff
        run: |
          pip install ruff
          ruff check .
      - name: black
        run: |
          pip install black
          black --check .
      - name: interrogate
        run: |
          pip install interrogate
          interrogate app/services -vv
