name: Code Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black interrogate

      - name: Check code style with Ruff
        run: ruff check .

      - name: Check formatting with Black
        run: black --check .

      - name: Check docstring coverage with Interrogate
        run: interrogate app/services -vv -f 100
